export const PETITION_LIST_REQUEST = "PETITION_LIST_REQUEST";
export const PETITION_LIST_SUCCESS = "PETITION_LIST_SUCCESS";
export const PETITION_LIST_FAIL = "PETITION_LIST_FAIL";
export const PETITION_CREATE_REQUEST = "PETITION_CREATE_REQUEST";
export const PETITION_CREATE_SUCCESS = "PETITION_CREATE_SUCCESS";
export const PETITION_CREATE_FAIL = "PETITION_CREATE_FAIL";
export const PETITION_CREATE_RESET = "PETITION_CREATE_RESET";
